version: "3.9"

services:
    flask_api:
        build:
            dockerfile: Dockerfile
        env_file:
            - .env
        container_name: ${APP_NAME}
        hostname: ${APP_NAME}
        depends_on:
            - film_db
        ports:
            - 8080:8080

        restart: always
        volumes:
            - /opt/data/${APP_NAME}/app:/data

    film_db:
        image: postgres:13.2
        restart: always
        container_name: film_db
        hostname: film_db_flask
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - ${DB_PORT}:5432
